### ISSUE TITLE
Request user guide

### ISSUE THREAD

**Issue by MoeinSarbandiiiii** [TUDelft-DataDrivenControl/FASTTool#6]
Hello

I am an beginner user and have trouble setting up and running.
I do the following process:
1. Open "FASTTool.m" & run it
2. Open Project "NREL5MW.mat" in FastTool
3. Calling data "NREL5MW.mat + NREL5MW_linearised.mat" in a workspace
4. Run FASTTool (Simulink)

But after running the simulation, I get a lot of errors.

Thank you for your help in the step-by-step process of using the toolbox or if you have any guidance, give it to me.

Thank you

**Comment by MoeinSarbandiiiii** [comment]
My email address if needed: **sarbandi_moein@email.kntu.ac.ir**

**Comment by akpamososuryo** [comment]
Hi @MoeinSarbandiiiii,

I am really sorry for not looking into this issue much earlier as I did not pay much attention to this part of the repository. So far we have not written a detailed user guide as this software is mainly used for teaching within our university. We normally teach the student to use this tool in a dedicated tutorial session.

That being said (and if you still need it), could you please elaborate on what sort of errors that you had so that I can help you? 

Again I apologize for this inconvenience.

Regards,
Atindriyo
